files:
  input: /Users/mlake/alleyway/add-tradingview-alerts-tool/ci_symbols.csv
  exclude: blacklist.csv
tradingview:
  chartUrl: https://www.tradingview.com/chart/EDlI2Ip1/
  interval: 4h
  username: absurdistcamus
  password:
alert:
  condition:
    primaryLeft: Price
    primaryRight: null
    secondary: Crossing Up
    tertiaryLeft: Value
    tertiaryRight: 1000000
    quaternaryLeft: null
    quaternaryRight: null
  trigger: Once only
  expireOpenEnded: false
  expireInterval: 24
  actions:
    notifyOnApp: true
    showPopup: true
    sendEmail: true
    webhook:
      enabled: true
      url: https://3commas.io/trade_signal/trading_view
    playSound:
      enabled: true
      name: Thin
      duration: Once
  message: |
    {
         "message_type": "bot",
         "bot_id": 999999,
         "email_token": "fffffff-fffff-fffff-ffff-ffffffffff",
         "delay_seconds": 0,
         "pair": "{{quote_asset}}_{{instrument}}"
    }
