#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node" "--no-warnings" "$basedir/node_modules/@alleyway/add-tradingview-alerts-tool/dist/cli.js" "$@"
  ret=$?
else
  node "--no-warnings" "$basedir/node_modules/@alleyway/add-tradingview-alerts-tool/dist/cli.js" "$@"
  ret=$?
fi
exit $ret
